version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: community_postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: community
      POSTGRES_PASSWORD: community
      POSTGRES_DB: community_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
